version: "2"

linters:
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-return
        severity: warning

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - goconst
        - gosec
        - revive
        - staticcheck
  max-issues-per-linter: 0
  max-same-issues: 0
